[workspace]
resolver = "2"
members = [
    "crystal-shared-proto",
    "crystal-server-net",
    "crystal-server-bin",
    "crystal-server-admin",
    "crystal-server-core",
    "crystal-server-db",
    "crystal-game-model",
    "crystal-content-cli",
    "crystal-content-pack",
    "crystal-client-bin",
    "crystal-client-app",
    "crystal-client-net",
    "crystal-client-config",
    "crystal-client-asset",
    "crystal-launcher-bin",
    "crystal-lib",
    "crystal-client-ui",
    "crystal-client-scene",
]
