#[derive(Clone, Debug)]
pub struct NpcInfo {
    pub index: i32,
    pub file_name: String,
    pub name: String,
    pub map_index: i32,
    pub location_x: i32,
    pub location_y: i32,
    pub rate: u16,
    pub image: u16,
    pub time_visible: bool,
    pub hour_start: u8,
    pub minute_start: u8,
    pub hour_end: u8,
    pub minute_end: u8,
    pub min_lev: i16,
    pub max_lev: i16,
    pub day_of_week: String,
    pub class_required: String,
    pub sabuk: bool,
    pub flag_needed: i32,
    pub conquest: i32,
    pub show_on_big_map: bool,
    pub big_map_icon: i32,
    pub can_teleport_to: bool,
    pub conquest_visible: bool,
    pub collect_quest_indexes: Vec<i32>,
    pub finish_quest_indexes: Vec<i32>,
}
