// Scene / object / combat related packets.
// These types are primarily defined in user.rs and npc.rs and re-exported here
// to group scene-related functionality under a dedicated module, similar to
// the C# GameScene organisation.

pub use crate::user::{
    SChat,
    SDeath,
    SDamageIndicator,
    SGainExperience,
    SGainHeroExperience,
    SGainedCredit,
    SGainedGold,
    SGainedItem,
    SColourChanged,
    SHeroHealthChanged,
    SHeroLevelChanged,
    SLevelChanged,
    SLoseCredit,
    SLoseGold,
    SObjectAttack,
    SObjectChat,
    SObjectDied,
    SObjectGold,
    SObjectHero,
    SObjectItem,
    SObjectGuildNameChanged,
    SObjectColourChanged,
    SObjectLeveled,
    SObjectHide,
    SObjectShow,
    SPoisoned,
    SObjectPoisoned,
    SObjectMonster,
    SObjectName,
    SRevived,
    SObjectRevived,
    SSpellToggle,
    SObjectHealth,
    SObjectMana,
    SRemoveDelayedExplosion,
    SObjectDeco,
    SObjectSneaking,
    SObjectLevelEffects,
    SSetConcentration,
    SSetElemental,
    SMountUpdate,
    STransformUpdate,
    SEquipSlotItem,
    SFishingUpdate,
    SSetBindingShot,
    SSwitchGroup,
    SDeleteGroup,
    SDeleteMember,
    SGroupInvite,
    SAddMember,
    SObjectPlayer,
    SObjectRemove,
    SObjectStruck,
    SObjectRun,
    SObjectTurn,
    SObjectTurnWalkRun,
    SObjectWalk,
    SPushed,
    SObjectPushed,
    SObjectSitDown,
    SInTrapRock,
    SUserBackStep,
    SObjectBackStep,
    SUserDash,
    SObjectDash,
    SUserDashFail,
    SObjectDashFail,
    SUserDashAttack,
    SObjectDashAttack,
    SUserAttackMove,
    SAllowObserve,
    STimeOfDay,
    SSendOutputMessage,
    SStruck,
    SObjectTeleportOut,
    SObjectTeleportIn,
    STeleportIn,
};

pub use crate::npc::{
    SConsignItem, SDefaultNpc, SMarketFail, SMarketSuccess, SObjectNpc, SNpcConsign,
    SNpcImageUpdate, SNpcMarket, SNpcMarketPage, SNpcResponse, SNpcUpdate, SRoll,
};
pub use crate::magic::{
    SNewMagic,
    SRemoveMagic,
    SMagicLeveled,
    SMagic,
    SMagicDelay,
    SMagicCast,
    SObjectMagic,
    SObjectEffect,
    SObjectProjectile,
    SRangeAttack,
    SObjectRangeAttack,
    SObjectSpell,
    SAddBuff,
    SRemoveBuff,
    SPauseBuff,
    SObjectHidden,
};
pub use crate::guild::{
    SGuildExpGain,
    SGuildInvite,
    SGuildMemberChange,
    SGuildNameRequest,
    SGuildNoticeChange,
    SGuildRequestWar,
    SGuildStatus,
    SGuildStorageGoldChange,
    SGuildStorageItemChange,
    SGuildStorageList,
};
pub use crate::stats::{SBaseStatsInfo, SHeroBaseStatsInfo, SUserName};
pub use crate::social::{
    SDivorceRequest, SMarriageRequest, SMentorRequest, STradeAccept, STradeCancel,
    STradeConfirm, STradeGold, STradeItem, STradeRequest,
};
pub use crate::hero::{
    SChangeHero,
    SHeroCreateRequest,
    SHeroInformation,
    SManageHeroes,
    SNewHero,
    SSetAutoPotItem,
    SSetAutoPotValue,
    SSetHeroBehaviour,
    SUnlockHeroAutoPot,
    SUpdateHeroSpawnState,
};
