// Scene / object / combat related packets.
// These types are primarily defined in user.rs and npc.rs and re-exported here
// to group scene-related functionality under a dedicated module, similar to
// the C# GameScene organisation.

pub use crate::user::{
    SChat,
    SDeath,
    SDamageIndicator,
    SGainExperience,
    SGainHeroExperience,
    SGainedCredit,
    SGainedGold,
    SGainedItem,
    SColourChanged,
    SHeroHealthChanged,
    SHeroLevelChanged,
    SLevelChanged,
    SLoseCredit,
    SLoseGold,
    SObjectAttack,
    SObjectChat,
    SObjectDied,
    SObjectGold,
    SObjectHero,
    SObjectItem,
    SObjectGuildNameChanged,
    SObjectColourChanged,
    SObjectLeveled,
    SObjectHide,
    SObjectShow,
    SPoisoned,
    SObjectPoisoned,
    SObjectMonster,
    SObjectPlayer,
    SObjectRemove,
    SObjectStruck,
    SObjectRun,
    SObjectTurn,
    SObjectTurnWalkRun,
    SObjectWalk,
    SUserDash,
    SObjectDash,
    SUserDashFail,
    SObjectDashFail,
    SStruck,
    SObjectTeleportOut,
    SObjectTeleportIn,
    STeleportIn,
};

pub use crate::npc::{SObjectNpc, SNpcResponse};
pub use crate::magic::{
    SNewMagic,
    SRemoveMagic,
    SMagicLeveled,
    SMagic,
    SMagicDelay,
    SMagicCast,
    SObjectMagic,
    SObjectEffect,
    SObjectProjectile,
    SRangeAttack,
    SObjectRangeAttack,
    SObjectSpell,
    SAddBuff,
    SRemoveBuff,
    SPauseBuff,
    SObjectHidden,
};
