[package]
name = "crystal-server-db"
version = "0.1.0"
edition = "2021"

[dependencies]
crystal-server-core = { path = "../crystal-server-core" }
rusqlite = { version = "0.31", features = ["bundled"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
tracing = "0.1"
