[package]
name = "crystal-server-bin"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net"] }
crystal-server-net = { path = "../crystal-server-net" }
crystal-shared-proto = { path = "../crystal-shared-proto" }
crystal-server-core = { path = "../crystal-server-core" }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
